name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build and Deploy
        run: |
          # Replace these commands with your build and deployment steps
          # For a simple static website, you might just copy files to the docs/ directory

          # Example for copying files (modify this based on your project structure):
          # mkdir docs
          # cp -r * docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Change this to your output directory
